### ISSUE TITLE
Sometimes, InfluxDB DAL timesout after just 2sec

### ISSUE THREAD

**Issue by AitorF** [DITAS-Project/ideko-use-case#5]
This is the error we get sometimes:

`Exception in thread "grpc-default-executor-29" java.lang.Error: java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]`

It seems that InfluxDB has no time to respond. Must be increased to a logical value, like 15.

**Comment by borjakhet** [comment]
In the `config/idekoDalGrpcServerConfig.yml` file, increment the `waitDuration` value.

Current setup: `waitDuration: 15 # seconds`
